### ISSUE TITLE
Basler : Long delay in Live mode after changing exposure time

### ISSUE THREAD

**Issue by soleil-ica** [esrf-bliss/Lima-camera-basler#17]
We have just encountered a problem when using a Basler camera in the "live" mode (using CtVideo->startLive())
The acquisition is started continuously with a certain "exposure time" (for example, 5 s) and during the acquisition, we need to change the "exposure time" (for example 200 ms) , we observe that the first image will only be available after an elapsed time equal to the previous "exposure time" ie 5s !!

This problem has existed for a long time, but we had never noticed before.

**Comment by laurent-claustre** [comment]
Sorry but I close it, no real an issue
