### ISSUE TITLE
software binning possible on basler?

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima-camera-basler#25]
Hello,
I was wondering if it is possible to use soft binning  in case of inappropriate hard binning.

Basler hardware 4x4 binning seems to take images with 12 bits pixels and merge 4 12 bits pixels (16 bits of information) into one 12 bits pixel (12 bits of information) so we loose 4 bits of information.

This 4 bits reduction of information is not a problem in case of low-signal detection but if we want to count a lot of signals, it become a problem.

Is there a solution to use soft binning on a basler, which allows hardware binning? I did not see anything about this in the doc.
Thank you.

edit : I use a camera [aca4024-29um](https://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace/aca4024-29um/) at 10Hz.
The goal is to compute a 16 bits images 4 times smaller than the original 12 bits image coded on 16 bits.

**Comment by laurent-claustre** [comment]
HI Philippe,
in LIma, by default we mixed software and hardware binning. It means you ask for a binning 4x4 and your camera is only supporting 2x2, lima will ask the camera to do 2x2 and lima will do 2x2 in addition to reach 4x4. In your case, you need to disable hardware binning and have only software binning to get 16bit binning.
In lima CtImage class we support 3 modes, SoftOnly,HardOnly and HardAndSoft, for both Binning and Roi operation. Default is HardAndSoft
Unfortunately this feature is not available from the tango server LimaCCDs. It can be added in the next release.

**Comment by PhilLAL** [comment]
Hi Laurent, 
my fault, I wrote a typo, I should have write 2x2 binning.
So I understand this is theoritically possible but not yet implemented and still need some work to be usable.

**Comment by PhilLAL** [comment]
Hi @laurent-claustre, 
since I need this feature for a local demo in 1 month, I would like to be sure of the best way to do this.

If I understand well, the work to make soft binning usable on basler could be limited to find some soft binning from another camera plugin and import it into camera plugin? This soft binning could be imported from a camera which already allow HardAndSoft mode or from a camera allowing SoftOnly ([Merlin](https://lima1.readthedocs.io/en/latest/camera/merlin/doc/index.html or [Dectris Eiger](https://lima1.readthedocs.io/en/latest/camera/eiger/doc/index.html) seems not allowing hw binning so they seem to be good candidate) .

Am I right?
Thank you.

**Comment by sebastien-petitdemange** [comment]
Hi Phil,

No you misunderstood, or Laurent wasn't clear enough 
Actually Lima library can switch to Software Binning (CtImage.setMode(
SoftOnly)) but it's not exported as an attribute in tango server.

So If you need it in you client somebody has to add a new attribute to
control the **image operation mode**.

SEB

P.S: I attached an untested patch which should do the jobs. Hops it helps.

[0001-added-an-attribute-to-control-image-operation.txt](https://github.com/esrf-bliss/Lima-camera-basler/files/2894606/0001-added-an-attribute-to-control-image-operation.txt)

**Comment by laurent-claustre** [comment]
Thanks, Seb, nice patch.

**Comment by PhilLAL** [comment]
Thank you Seb. :)

**Comment by laurent-claustre** [comment]
Hi Phil, 
some good news on your side? did you test the patch? 
I would like to merge and make a new conda package for lima-tango-python .

**Comment by PhilLAL** [comment]
Hi Laurent, I finish the installation of a new computer to test it. I'll come back as soon as I test it.
Thanks.

**Comment by PhilLAL** [comment]
Hi, sorry for letting you without news. 
I'm sorry since I can't currently test it yet because I use a usb camera (see #26) which is not yest supported.

**Comment by laurent-claustre** [comment]
Hi Phil, i close this issue and if you hae a chance to test the patch, please open a new issue in applications/tango/python, more relevant.
Cheers

**Comment by PhilLAL** [comment]
Ok, thank you Laurent.
