### ISSUE TITLE
usb support for basler

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima-camera-basler#26]
Hello,
I open this ticket here since it is more appropriate.

@laurent-claustre wrote in a [Lima](https://github.com/esrf-bliss/Lima/issues/85#issuecomment-474398944) ticket that usb is not supported but some code exists to add usb support for basler.

Our users have bought a USB Basler Ace camera ([acA4024-29um](https://www.baslerweb.com/en/products/cameras/area-scan-cameras/ace/aca4024-29um/#tab=specs)) since they wanted high dynamic and high frequency (I am still looking if another model would not be better choice), so it could interest me if USB support is available.

Regards.

**Comment by PhilLAL** [comment]
Hi @laurent-claustre 
do you think this is possible to add usb support in a short delay? To explain our situation, a new project has begun and need a usb basler with binning. 
Since we know LImA and we used it with Basler camera, we suggested to use it so. However, it seems it cannot currently be used for usb basler camera, and I would like to understand if this would be added or if we should think about another solution.

Thank you.

**Comment by laurent-claustre** [comment]
Hi Philippe,
The code for usb is 2 years old, and need some work to be merged with current one. I do not have time this month. Sorry.

**Comment by PhilLAL** [comment]
Hi Laurent,
thank you anyway for your answer.

**Comment by PhilLAL** [comment]
Hello @laurent-claustre 
we decided to first test with an ethernet basler, but since I will buy the computer which will be used with LImA, I wondered if a LImA USB is still in work in progress and if you have any idea about the ressources needed to run this LImA version. :)

Regards.

**Comment by laurent-claustre** [comment]
Hi Philippe,
no progress on Basler USB. It is in low priority here at ESRF. If someone can help outsite?
About computer resources, difficult to say. If you can run your camera using PylonViewerApp at full speed, Lima will do the job.

**Comment by PhilLAL** [comment]
Thank you for this, good point for Pylon, it will get met a point of comparison:)

**Comment by PhilLAL** [comment]
Hello @laurent-claustre I understand this is low priority but I wondered if there are some news about usb support?
Thanks.

**Comment by laurent-claustre** [comment]
Hi,
there are USB3 basler coming at ESRF, but not before 2021/01. We will then work on this.
That can take longer than expected if we decide to port Basler plugin to the latest Pylon5 sdk high level API.

**Comment by PhilLAL** [comment]
Thank you for those details @laurent-claustre

**Comment by PhilLAL** [comment]
Hi Laurent,
I just realized that a pylon6 version is available on https://www.baslerweb.com/en/sales-support/downloads/software-downloads/#type=pylonsoftware;version=5.2.0;os=linuxx86
Don't know if it can be useful, if you want to include last sdk version.

**Comment by PhilLAL** [comment]
Hi @laurent-claustre, 
pandemic added some delays to our projects, and I wonder if you already had some results with USB3 basler?
Regards

**Comment by laurent-claustre** [comment]
Salut Philippe,
yes, good new we have now, pretty soon, an updated code for basler using Pylon6, and supporting USB3 cameras.
We will provide in the coming weeks new conda packages for both linux and windows.

**Comment by PhilLAL** [comment]
Great news! Can't wait for it, thank you for your answer!
