### ISSUE TITLE
Last image in buffer seems to not be the real last one (not the most recent one)

### ISSUE THREAD

**Issue by smaluli** [esrf-bliss/Lima-camera-basler#27]
Hi all,

We at LULI currently using an old version of Lima (1.4.? from 2015) and we have issues with the last image recorded…which is not always the more recent one. It causes delay in display from zero to few images with random behaviour.
We then try to install the last version of Lima and the lima-camera-basler-tango plugin (thanks to samuel) and test this install with a Basler camera on External Trigger (EXTERNAL_GATE) at a 10-second rate looking at a PC Windows clock. At the same time, we're using a LabView binding to read a part of the buffer.

And this is the result of a 20+ minutes testing which represents 151 images:

![buffer_lima](https://user-images.githubusercontent.com/39699662/52220111-6a9b0980-289e-11e9-9030-408643ea8960.jpg)

(Sorry, the two tabs rows don't match each other but it's not important.)
As you can barely see (!) the first one on the left reads "16:03:21" as the 9th from the left reads "16:04:41" (aka the near real time). You can guess the getImage(-1) in Lima reads the left one: the last_image_acquired here is No. 151. And we do not have any clue to guess the No. of the real last image acquired (here the No.143 but it fluctuates from 1 to the buffer's size, randomly). You can imagine the users' state of mind when they're trying to align a laserbeam with 10Hz to 0.016Hz rate. It's very confusing even with the minimum size of buffer (1%, 16 to 7 images' pile depending architecture).

(We tried on INTERNAL_TRIGGER mode and for the minimum size of buffer (1%) but the behaviour, as not predictable and less easy to capture, will results in the same way: randomly lost--or rather misplaced--of last image.)

Is this behaviour is already known?
Thanks for any help!
Stéphane

**Comment by laurent-claustre** [comment]
Hi Stephane,
I did move the issue the basler project, more relevant for us.

New packages are available, version 1.8.1 on anaconda esrf-bcu channel.

You can just update lima-camera-basler package or reinstall from scratch by first removing all the lima packages and then just install lima-camera-basler-tango which pull the others by deps.

Cheers.

**Comment by smaluli** [comment]
Hi Laurent,
Thank you so much! The installation is complete (and so easy).
We did some tests at 10Hz in INTERNAL_TRIGGER or EXTERNAL_GATE and it seems fine with less lost packets than before. We have some issues on our side (synchro of the camera and VM rules), I'll process this on Monday: I'll give you more feedback then.
Still, I didn't get the idea behind the test_image_selector: would you explain the TESTIMAGE_[OFF|1|2|…] options?
-- when I select TESTIMAGE_[1|…]  I saw no real image, just some gap for each failed buffer count on the test image:
-- when I select TESTIMAGE_OFF I saw no real effect between ok/failed but again I'm locked at 10Hz if trigged so not the easiest way to check this.

So the next question is what's the impact of a lost packet (or failed buffering): the last image is still put in the first place of buffer like a complete one? And then we miss some pixels corresponding of the lost packets?

And extra question from Jean-Luc: did you made some modifications with the size of the image in 8 bits?

Have a good week-end

**Comment by laurent-claustre** [comment]
Hi Stephane,,
* yes TestImageSelector is only useful to test your camera with NO IMAGE, you get a mire image with fix pattern or changing  pattern to test your software if you cannot get something visible. Please refer to the Pylon documentation for more information.
* about the fix for lost packet, we do not copy the previous image, but just wait for the next valid one. That means if you watch a clock you will just miss some time but in the correct order, not like before where you get mixed of time.
* about 8 bit, no way to switch using image_type, instead you should use the video_mode attribute, check if your camera provide y8 y16 mode.

**Comment by smaluli** [comment]
Thank you again, Laurent, for all the details. I had a little time to test yesterday pm but I saw nothing weird so it's a very great improvement for us! I'll continue the tests today and tomorrow before putting this version into an operational mode.

**Comment by laurent-claustre** [comment]
I Stephane, on my side it is now ok to close the issue. thanks for your help.
