### ISSUE TITLE
setFrameRate() not supported

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima-camera-basler#28]
Hi,
launching a LimaCCDs DS, I noticed a warning message : 
```
$ LimaCCDs ccdsst1-tl
basler camera_id: ccdsst1-tl.thomx.fr
ctcontrol.accumulation() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd324ad7d68>
ctcontrol.acquisition() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd31515c2b0>
ctcontrol.buffer() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd31516db38>
ctcontrol.config() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd315177710>
ctcontrol.event() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd3151811d0>
ctcontrol.image() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd315181e10>
ctcontrol.saving() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd3151928d0>
ctcontrol.shutter() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd31512a710>
ctcontrol.video() = <Lima.Server.EnvHelper.to_tango_object.<locals>.klass object at 0x7fd315181550>
In  tl/bpm/sst.01-ccd.01 ::init_device()
Warning: setFrameRate() not supported
[2019/09/09 14:21:42.444591] 7fd33d440580 *Application*Lima.Server.LimaCCDs::LimaCCDs::apply_config-Always: Applied config : lima_config.cfg : default 
```

Searching into the doc, I noticed a `setFrameRate() not supported` warning message, but `setFrameRate` is only mentionned for PointGrey camera (https://lima1.readthedocs.io/en/latest/camera/pointgrey/doc/index.html?highlight=setframerate#specific-control-parameters).

I never noticed this warning message but trying another camera, I confirm it appears with some others Basler camera (we currently only have this model).

Do you have any idea why it appears and how to make it disappear?
Regards.

**Comment by laurent-claustre** [comment]
Hi Philippe,
this message comes from plugin/LiveViewer.py plugin device. 
This plugin is obsolete and we do not provide it within conda packages. Nevertheless we keep it on the source repository, if you do not need it we strongly suggest to remove it from your installation.

**Comment by PhilLAL** [comment]
Hi Laurent, thank you for these details.

I understood from https://github.com/esrf-bliss/Lima/issues/101 that this DS was only forgotten in the distribution. 
Does it mean this will not be integrated into next package lima-tango-server?
Our users love it. :)

**Comment by PhilLAL** [comment]
Hi Laurent,

I noticed there are two device allowing displaying the current acquired image : 
- LimaViewer DS 
- LiveViewer subdevice in LimaCCDs DS.
I was confused in my former [message](https://github.com/esrf-bliss/Lima-camera-basler/issues/28#issuecomment-529479434) because of the similar names but I understand from your [answer](https://github.com/esrf-bliss/Lima-camera-basler/issues/28#issuecomment-529462318) that LiveViewer subdevice is obsolete and will disappear, and from you message in another [issue](https://github.com/esrf-bliss/Lima/issues/101) that LimaViewer was not anymore in conda package

I understand we can use LiveViewer for the moment, but we should use LimaViewer as soon as this package is reintegrated into the conda package. Am I right?
Thank you and happy new year.

**Comment by laurent-claustre** [comment]
Hi Philippe,
sorry for the late answer. My last message was a bit confusing and with mistakes. I fact we continue to provide both LimaViewer exec and LiveViewer plugin, so will free to use what ever you need.
I last conda package we clean useless  print/trace like about FrameRate.

**Comment by PhilLAL** [comment]
Great, thank you.
