### ISSUE TITLE
mamba installation of Lima on windows 10 can't connect to Basler acA640-100gm

### ISSUE THREAD

**Issue by keale** [esrf-bliss/Lima-camera-basler#36]
Dear all,
related to issue esrf-bliss/Lima#141.

I have installed Lima on a Windows 10 PC with mamba 
(lima-camera-basler 1.10.9 lima-camera-basler-tango 1.10.10 0 lima-core 1.9.15 lima-tango-server 1.9.20).

The DB device server is runing on a Ubuntu 22.04 VM, see esrf-bliss/Lima#141. 
When I try to start a device server for **acA640-100gm** on windows pc, I get the error message:
````
(basler) C:\Users\AlexK>LimaCCDs 1
basler camera_id: ip://192.168.50.220
[2024/01/15 12:31:46.707438] 1e8ace3c270     *Camera*lima::Basler::Camera::Camera (\BaslerCamera.cpp:310)-Always: No Camera found!
[2024/01/15 12:31:46.708412] 1e8ace3c270     *Camera*lima::Basler::Camera::Camera (\BaslerCamera.cpp:324)-Error: Exception(Error):  [thrown]
*********     No device is available or no device contains the provided device info properties.
-------> Received a DevFailed exception: DevFailed[
DevError[
    desc = limacore.Exception: Hardware: lima::Basler::Camera::Camera(C:\Mambaforge\conda-bld\lima-camera-basler_1698770569337\work\src\BaslerCamera.cpp, 324): Error: No device is available or no device contains the provided device info properties.
````
I can start LimaCCD for the cam on the VM and a LimaViewer on Windows.

P.S.
In general, everything from TANGO (show and refresh in jive, LimaCCDs in Terminal) reacts very slowly on Windows, as if some timeout must occur first. In the VM they react immediately.

**Comment by laurent-claustre** [comment]
ok thanks. Finally I did a test on a windows computer and get the same issue as you. So I gonna investigate now and I will come back to you once I can propose the fix.

**Comment by keale** [comment]
Thank You Laurent!

**Comment by laurent-claustre** [comment]
Ok I find the pb, it comes from the conda package pylon6-sdk version 6.3.0 (made by us) to redistribute the pylon libraries, there are missing dll. I will prepare a new version 6.3.1 and remove the previous one from anaconda esrf-bcu channel.
coming soon ...

**Comment by laurent-claustre** [comment]
So I did push a new package pylon6-sdk 6.3.1 on anaconda esrf-bcu channel and remove 6.3.0 (only for windows).

Simply remove your basler environment and create a new one: 

```
(base) C:\Users\opid00> mamba create -n basler lima-camera-basler-tango -c esrf-bcu
```

You should get the following (lima) package installed:

```
(basler) C:\Users\opid00>conda list lima
# packages in environment at C:\Miniconda3\envs\basler:
#
# Name                    Version                   Build  Channel
lima-camera-basler        1.10.10          py39h2e52968_0    esrf-bcu
lima-camera-basler-tango  1.10.10                       0    esrf-bcu
lima-core                 1.9.23           py39h2e52968_0    esrf-bcu
lima-tango-server         1.9.20                     py_0    esrf-bcu
```

+ the good pylon6 package:

```
(basler) C:\Users\opid00>conda list pylon
# packages in environment at C:\Miniconda3\envs\basler:
#
# Name                    Version                   Build  Channel
pylon6-sdk                6.3.1                         0    esrf-bcu
```

**Comment by keale** [comment]
Thanks a lot, it works now!
